# GitHub Sponsors configuration
# Replace these with your own usernames/links when ready

# github: your-username  # Uncomment and add your GitHub Sponsors username
# patreon: your-username  # Uncomment and add your Patreon username
# custom: ["https://your-donation-link.com"]  # Uncomment and add custom donation links
